version: "3.7"

services:
  builder:
    container_name: builder
    build:
      dockerfile: Dockerfile
    image: ian
    volumes:
      - ..:/home/ian/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/home/ian/.ssh
      # Shell history persistence
      - ~/.zsh_history:/home/ian/.zsh_history
      # Git config
      - ~/.gitconfig:/home/ian/.gitconfig
      # ccache
      - ~/.ccache:/home/ian/.ccache
      # GUI
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /dev/shm:/dev/shm
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Pacific/Auckland
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    privileged: true
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - seccomp=unconfined
